version: '3'

services:
  db:
    image: mdillon/postgis
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cykel
      - POSTGRES_PASSWORD=password
  cykel:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=fooooo
      - ALLOWED_HOSTS=0.0.0.0,localhost
      - DEBUG=1
      - DATABASE_URL=postgis://postgres:password@db:5432/cykel
    depends_on:
      - db

volumes:
  data:
